# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c667fca8d78298e987cdecacb65956c636bbd9879eb39cbc0a4e15cbb700f64c5c193b9198396ca9450769d8d90ce0bdc5364f5728056f1b5caf4ae845821fa

test:
  secret_key_base: b03e38b56293fc1b9022a98db885eb6468157b9d188d463eb320b63682847c539d5496d9b34cf17f2086b500f2c2788485b4d55f32b9eaf6e638143721f658fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
